apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api2
spec:
  selector:
    matchLabels:
      app: simple-api2
  template:
    metadata:
      labels:
        app: simple-api2
    spec:
      containers:
      - name: simple-api2
        image: omidiyanto/go-simple-api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: simple-api2-service
spec:
  selector:
    app: simple-api2
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-api2-ingress
  labels:
    name: simple-api2-ingress
  annotations:
    haproxy.org/path-rewrite: "/app2(.*) \\1"
spec:
  rules:
  - host: simple-api.com
    http:
      paths:
      - pathType: Prefix
        path: "/app2"
        backend:
          service:
            name: simple-api2-service
            port:
              number: 8080

